  CREATE TABLE WEEKLY_DAILY(
    WEEKLY_ID BIGINT NOT NULL,
    DAILY_ID BIGINT NOT NULL
  );

  CREATE TABLE FOLLOWED_DIETS(
    CLIENT_ID BIGINT NOT NULL,
    DIET_ID BIGINT NOT NULL
  );

  CREATE TABLE BUSINESS(
    ID BIGINT NOT NULL,
    BUSINESS_NAME VARCHAR(255) NOT NULL
  );

	CREATE TABLE RECIPES(
    RECIPE_ID BIGINT,
    PROFESSIONAL_ID BIGINT,
    IMAGE_DATA BLOB,
    RECIPE_DESCRIPTION VARCHAR(255),
    RECIPE_NAME VARCHAR(255),
    CALORIES VARCHAR(255),
    CARBS VARCHAR(255),
    COOKING_TIME VARCHAR(255),
    FAT VARCHAR(255),
    PRICE VARCHAR(255),
    PROTEIN VARCHAR(255),
    RECIPE_TYPE VARCHAR(255)
  );

	CREATE TABLE LINKED_ROUTINES(
    USER_ID BIGINT NOT NULL,
    ROUTINE_ID BIGINT NOT NULL
  );

	CREATE TABLE FOLLOWERS(
    PROFESSIONAL_ID BIGINT NOT NULL,
    FOLLOWER_ID BIGINT NOT NULL
  );

	CREATE TABLE RECIPE_INGREDIENTS(
    RECIPE_RECIPE_ID BIGINT NOT NULL,
    INGREDIENTS VARCHAR(255)
  );

	CREATE TABLE FOLLOWED_EXERCISES(
    CLIENT_ID BIGINT NOT NULL,
    ROUTINE_ID BIGINT NOT NULL,
    EXERCISE_ID BIGINT NOT NULL
  );

	CREATE TABLE LINKED_DIETS(
    USER_ID BIGINT NOT NULL,
    DIET_ID BIGINT NOT NULL
  );

	CREATE TABLE DAILY_DIET(
    DAILY_ID BIGINT NOT NULL,
    DIET_ID BIGINT NOT NULL
  );

	CREATE TABLE EXERCISE_EQUIPMENTS(
    EXERCISE_EXERCISE_ID BIGINT NOT NULL,
    EQUIPMENTS VARCHAR(255)
  );

	CREATE TABLE ROUTINES(
    ROUTINE_ID BIGINT,
    ROUTINE_DESCRIPTION VARCHAR(255),
    ROUTINE_NAME VARCHAR(255),
    PROFESSIONAL_ID BIGINT,
    NUMBER_SERIES VARCHAR(255),
    EXPECTED_TIME VARCHAR(255),
    RESTING_TIME VARCHAR(255)
  );

  CREATE TABLE ROUTINE_EXERCISE(
    ROUTINE_ID BIGINT NOT NULL,
    EXERCISE_ID BIGINT NOT NULL
  );

  CREATE TABLE EXERCISES(
    EXERCISE_ID BIGINT,
    PROFESSIONAL_ID BIGINT,
    EXERCISE_NAME VARCHAR(255),
    EXERCISE_DESCRIPTION VARCHAR(255),
    IMAGE_DATA BLOB,
    BODY_PART VARCHAR(255),
    TOOLS VARCHAR(255),
    NUMBER_REPETITIONS VARCHAR(255),
    RESTING_TIME VARCHAR(255)
  );


	CREATE TABLE RECIPE_TOOLS(
    RECIPE_RECIPE_ID BIGINT NOT NULL,
    EQUIPMENT VARCHAR(255),
    TOOLS VARCHAR(255)
  );

	CREATE TABLE PROFESSIONALS_CLIENTS(
    PROFESSIONAL_ID BIGINT NOT NULL,
    CLIENT_ID BIGINT NOT NULL
  );

	CREATE TABLE WEEKLY(
    WEEKLY_ID BIGINT,
    PROFESSIONAL_ID BIGINT
  );

	CREATE TABLE DAILY(
    DAILY_ID BIGINT,
    WEEK_DAY VARCHAR(255),
    PROFESSIONAL_ID BIGINT,
    DIET_ID BIGINT,
    ROUTINE_ID BIGINT
  );

	CREATE TABLE PROFESSIONALS(
    RATING INTEGER,
    WORK_ZONE VARCHAR(255),
    USER_ID BIGINT NOT NULL,
    BUSINESS_ID BIGINT,
    PUBLIC BOOLEAN,
    TYPE VARCHAR(255)
  );

	CREATE TABLE LINKED_DAILIES(
    USER_ID BIGINT NOT NULL,
    DAILY_ID BIGINT NOT NULL
  );

  CREATE TABLE MODEL_USERS(
    USER_ID BIGINT,
    BIRTH_DATE DATE,
    EMAIL VARCHAR(255),
    ENABLED BOOLEAN,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    USER_NAME VARCHAR(255),
    ROLE_ID BIGINT
  );

	CREATE TABLE EXERCISE_BODY_PARTS(
    EXERCISE_EXERCISE_ID BIGINT NOT NULL,
    BODY_PART VARCHAR(255),
    BODY_PARTS VARCHAR(255)
  );

	CREATE TABLE FOLLOWED_RECIPES(
    CLIENT_ID BIGINT NOT NULL,
    ROUTINE_ID BIGINT NOT NULL,
    RECIPE_ID BIGINT NOT NULL
  );

	CREATE TABLE EXERCISE_EQUIPMENT(
    EXERCISE_EXERCISE_ID BIGINT NOT NULL,
    EQUIPMENT VARCHAR(255)
  );

	CREATE TABLE VERIFICATION_TOKEN(
    TOKEN_ID BIGINT,
    EXPIRE_AT TIMESTAMP NOT NULL,
    TIME_STAMP TIMESTAMP,
    TOKEN VARCHAR(255),
    USER_ID BIGINT
  );

	CREATE TABLE FOLLOWED(
    PROFESSIONAL_ID BIGINT NOT NULL,
    FOLLOWER_ID BIGINT NOT NULL,
    FOLLOWED_ID BIGINT NOT NULL
  );

	CREATE TABLE DAILY_ROUTINE(
    DAILY_ID BIGINT NOT NULL,
    ROUTINE_ID BIGINT NOT NULL
  );

	CREATE TABLE ROLES(
    ROLE_ID BIGINT,
    ROLE_DESCRIPTION VARCHAR(255) NOT NULL
  );

	CREATE TABLE LINKED_CLIENT_ROUTINES(
    USER_ID BIGINT NOT NULL,
    ROUTINE_ID BIGINT NOT NULL
  );

	CREATE TABLE DIET_RECIPE(
    DIET_ID BIGINT NOT NULL,
    RECIPE_ID BIGINT NOT NULL
  );

  CREATE TABLE LINKED_WEEKLIES(
    USER_ID BIGINT NOT NULL,
    WEEKLY_ID BIGINT NOT NULL
  );

  CREATE TABLE FOLLOWED_PLANS(
    CLIENT_ID BIGINT NOT NULL,
    ROUTINE_ID BIGINT NOT NULL,
    WEEKLY_ID BIGINT NOT NULL
  );

	CREATE TABLE FAVOURITE_CLIENT_EXERCISES(
    USER_ID BIGINT NOT NULL,
    EXERCISE_ID BIGINT NOT NULL,
    CLIENT_ID BIGINT NOT NULL
  );

	CREATE TABLE FOLLOWED_ROUTINES(
    CLIENT_ID BIGINT NOT NULL,
    ROUTINE_ID BIGINT NOT NULL
  );

  CREATE TABLE FAVOURITE_CLIENT_RECIPES(
    USER_ID BIGINT NOT NULL,
    RECIPE_ID BIGINT NOT NULL,
    CLIENT_ID BIGINT NOT NULL
  );

	CREATE TABLE DIETS(
    DIET_ID BIGINT,
    DIET_DESCRIPTION VARCHAR(255),
    DIET_NAME VARCHAR(255),
    PROFESSIONAL_ID BIGINT
  );

  CREATE TABLE CLIENTS(
    WORK_ZONE VARCHAR(255),
    USER_ID BIGINT NOT NULL,
    WEEKLY_ID BIGINT
  );